### PR TITLE
Upgrading to Twemoji v2

### PR DESCRIPTION
**Pull request by kamalasaurus**
Hi!  This ended being more of a project than I thought it would be.

I created a git submodule for your project called twemoji-possum: https://github.com/kamalasaurus/twemoji-possum

This will scrape the active and currently deployed unicode tables and twemoji distributions to automatically assign human readable class names to all the icons.  Some of the names are kind of clunky, so it's possible to add custom names.  The README for twemoji-possum details how I dealt with collisions from the emoji-cheat-sheet namespace and future extensibility.

If you want a preview of the class names to the icons go to the handy cheat sheet!  https://kamalasaurus.github.io/twemoji-awesome-cheatsheet/

The source is hosted:  https://github.com/kamalasaurus/twemoji-awesome-cheatsheet

I will update the submodule for the cheat sheet to point at the official twemoji-awesome repo if/when this pull request is approved; it is currently pointing at my fork!

I moved your current setup into the `v1` folder for posterity.  Please let me know if you have any questions!

### CODE REVIEW

**Comment by kamalasaurus** [comment]
Hey Elle,

Thanks for merging the PR!

I noticed that you're not actively maintaining the repo anymore, can you
add me as a collaborator so I can do stuff like link the new cheatsheet for
2.0 and stuff?

Thanks for coming out of open-source retirement for my random update 😁!

-Kamal

**Comment by kamalasaurus** [comment]
Ah!

Nevermind, you already did!  Gmail just moved the invite to a weird place.

Thanks!

-Kamal

**Comment by James-Bovis** [comment]
Hi @kamalasaurus,

Just wanted to ask, are you looking at updating Twemoji to version 2.2 just released by Twitter? Would be great to see this project updated :) 👍 

Thanks,
James

**Comment by kamalasaurus** [comment]
Ah!

Thanks for the heads up!  Hmm...  I'm digging around a bit on the twemoji repo, the latest distribution appears to be 2.2.2, but they don't seem to host test previews for fractional versions.  I'll try to dig in a bit over the next couple of days, but I may have to change the parsing approach.

Feel free to ping me again if it seems like it dropped off my radar!

Out of curiosity, what emojis are you most looking forward to from 2.2.x?  😃

-Kamal

**Pull request merged**
